\context ChordNames
	\chords {
		% intro
		\skip 2*1
		\skip 2*8

		% Tu y yo...
		\break
		\skip 2*7
		\break
		\skip 2*7

		% Haremos uno hogar de fe...
		\break
		\skip 2*4
		\break
		\skip 2*4

		% Confiaremos...
		\break
		\skip 2*4
		\skip 2*4

		% interludio
		\break
		\skip 2*4
		\skip 2*4

		% Y asi...
		\break
		\skip 2*7
		\break
		\skip 2*7

		% Haremos uno hogar de fe...
		\break
		\skip 2*4
		\break
		\skip 2*4

		% Confiaremos...
		\break
		\break
		%\skip 2*4
	}
