\context ChordNames
	\chords {
		\set Score.markFormatter = #format-mark-box-numbers

		% intro
		\mark \default
		\skip 2*1
		\skip 2*8

		% Tu y yo...
		\mark \default
		\skip 2*14

		% Haremos uno hogar de fe...
		\mark \default
		\skip 2*4
		\skip 2*4

		% Confiaremos...
		\mark \default
		\skip 2*4
		\skip 2*4

		% interludio
		\mark \default
		\skip 2*4
		\skip 2*4

		% Y asi...
		\mark \default
		\skip 2*14

		% Haremos uno hogar de fe...
		\mark \default
		\skip 2*4
		\skip 2*4

		% Confiaremos...
		\mark \default
		\skip 2*4
		\skip 2*4
	}
