\context ChordNames
	\chords {
		\set chordChanges = ##t
		% intro
		R1
		c2 d2
		g2 e2:m
		c2 d2
		g1

		% tu y yo...
		e2:m c2 d2 g2 c2 d2
		d2 c4 d4 e2:m d2
		e2:m c2
		d1

		% haremos...
		c2 d2
		g2 e2:m
		c2 a2:m7
		d1

		% confiaremos...
		c2 d2
		g2 e2:m
		c2 d2
		g1

		% interludio
		c2 d2
		g2 e2:m
		c2 d2
		g1

		% y así...
		e2:m c2 d2 g2 c2 d2
		d2 c4 d4 e2:m d2
		e2:m c2
		d1

		% haremos...
		c2 d2
		g2 e2:m
		c2 a2:m7
		d1

		% confiaremos...
		c2 d2
		g2 e2:m
		c2 d2
		g1
	}
